### ISSUE TITLE
Index out of Bounds Exception when passing GaugeNumerics a valueRange which does NOT start with 0

### ISSUE THREAD

**Issue by SkyeGamesStudio** [yamin8000/Gauge#25]
I fixed it by adding:
` - numerics.valueRange.start.toInt() `
to line 276 of Gauge.kt to make the full line look like this:
![image](https://github.com/yamin8000/Gauge/assets/142793742/85a2a12a-d447-4aac-b9bb-d660a0c493da)

Hope this helps!
Great Gauge BTW!

**Comment by yamin8000** [comment]
> I fixed it by adding: `- numerics.valueRange.start.toInt()` to line 276 of Gauge.kt to make the full line look like this: ![image](https://private-user-images.githubusercontent.com/142793742/324453633-85a2a12a-d447-4aac-b9bb-d660a0c493da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTQ2NDMsIm5iZiI6MTcxMzkxNDM0MywicGF0aCI6Ii8xNDI3OTM3NDIvMzI0NDUzNjMzLTg1YTJhMTJhLWQ0NDctNGFhYy1iOWJiLWQ2NjBhMGM0OTNkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMzE5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTNkNTY2YmViZDUyNDI4NjE3ZDcwYjdkMWM4ODY1NjU3ZWJlNWQ3NjJjMWVmNmY2NmZhZjAxOWI0ZTczMmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ihKbCN_GvlX20JF7oVsoQgcR64lDEQSG_LU8zvhLnS4)
> 
> Hope this helps! Great Gauge BTW!

Hi
You're right.
Thank you for this. Great find.
It's either your fix or this:
```kotlin
val tickColor = if (isBigTick) colors.bigTicks
else ticksColors.find { it.first == value }?.second ?: colors.smallTicks
```
However, I think yours have a better performance. It has a benefit of not using an unnecessary loop to find the value.
```kotlin
val tickColor = if (isBigTick) colors.bigTicks
else ticksColors[value - numerics.valueRange.start.toInt()].second
```
